//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paylasimProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectPaylasimEntities6 : DbContext
    {
        public projectPaylasimEntities6()
            : base("name=projectPaylasimEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mesajlar> mesajlars { get; set; }
        public virtual DbSet<rezerv> rezervs { get; set; }
        public virtual DbSet<urun> uruns { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<yorum> yorums { get; set; }
    }
}
